spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:54320/test?schema=webflux
        username: user
        password: admin

logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: DEBUG