spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:54320/test?schema=webflux
        username: <user>
        password: <admin>
    flyway:
        url: jdbc:postgresql://localhost:54320/test
        user: ${spring.r2dbc.username}
        password: ${spring.r2dbc.password}
        schemas:
          - webflux
        baselineOnMigrate: true
        enabled: true
        
springdoc:
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: DEBUG